
###################################################
#
# file: Makefile
#
# @Author:   Iacovos G. Kolokasis
# @Version:  10-02-2022
# @email:    kolokasis@csd.uoc.gr
#
# Makefile
#
####################################################

####################################################
# Makefile for Assignment 4: Sudoku
####################################################

# Compiler and flags
CC      := gcc
CFLAGS  := -Wall -ansi -pedantic -MMD -MP

# Directories
SRC_DIR := src
BUILD_DIR := build

# Sources, objects, deps
SRCS    := $(wildcard $(SRC_DIR)/*.c)
OBJS    := $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
DEPS    := $(OBJS:.o=.d)

# Executable
EXEC    := sudoku

.PHONY: all clean

all: $(EXEC)

# Link
$(EXEC): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

# Compile each .c into build/%.o, generate .d files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Ensure build directory exists
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Include autogenerated dependency files
-include $(DEPS)

clean:
	rm -rf $(BUILD_DIR) $(EXEC)

